### ISSUE TITLE
Build App Error: NameError: name 'Distribution' is not defined

### ISSUE THREAD

**Issue by rutopio** [r0x0r/pywebview-react-boilerplate#27]
I have followed the README tutorial to build the apps, and it worked when running `npm run start`. However, I encountered an error after building the app (`npm run build`). Upon launching, the following screen capture shows the issue:

![ScreenCapture](https://github.com/r0x0r/pywebview-react-boilerplate/assets/22339116/fd700dc9-51a3-4d56-9055-eb35a6d1dd50)

When I attempt to launch `/pywebview-react-boilerplate-master/dist/index.app/Contents/MacOS/index` directly in the terminal, the following error is displayed:

```

user@userMacbookPro ~ % /Users/user/Downloads/pywebview-react-boilerplate-master/dist/index.app/Contents/MacOS/index
/Users/user/Downloads/pywebview-react-boilerplate-master/dist/index.app/Contents/Resources/__boot__.py:116: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
Traceback (most recent call last):
  File "/Users/user/Downloads/pywebview-react-boilerplate-master/dist/index.app/Contents/Resources/__boot__.py", line 144, in <module>
    _fixup_pkg_resources()
  File "/Users/user/Downloads/pywebview-react-boilerplate-master/dist/index.app/Contents/Resources/__boot__.py", line 142, in _fixup_pkg_resources
    list(map(pkg_resources.working_set.add_entry, sys.path))
  File "pkg_resources/__init__.pyc", line 671, in add_entry
  File "/Users/user/Downloads/pywebview-react-boilerplate-master/dist/index.app/Contents/Resources/__boot__.py", line 126, in find_eggs_in_zip
    yield Distribution.from_filename(path_item, metadata=metadata)
          ^^^^^^^^^^^^
NameError: name 'Distribution' is not defined
2023-12-07 15:02:55.839 index[23367:11064902] Launch error
2023-12-07 15:02:55.839 index[23367:11064902] Launch error
See the py2app website for debugging launch issues
```

My platform details are as follows:

- MacBook Pro (13-inch, M1, 2020)
- macOS 12.6（21G115）Monterey
- Python 3.11.0 (under venv-pywebview environment)

Any suggestions are welcome. Thank you.

**Comment by rutopio** [comment]
To solve it, add `pkg_resources` module name in front of `Distribution.from_filename(path_item, metadata=metadata)` in line 188 that:

```python
import pkg_resources, zipimport, os


def find_eggs_in_zip(importer, path_item, only=False):
    if importer.archive.endswith('.whl'):
        # wheels are not supported with this finder
        # they don't have PKG-INFO metadata, and won't ever contain eggs
        return

    metadata = pkg_resources.EggMetadata(importer)
    if metadata.has_metadata('PKG-INFO'):
        yield pkg_resources.Distribution.from_filename(path_item, metadata=metadata)
    for subitem in metadata.resource_listdir(''):
        if not only and pkg_resources._is_egg_path(subitem):
            subpath = os.path.join(path_item, subitem)
            dists = find_eggs_in_zip(zipimport.zipimporter(subpath), subpath)
            for dist in dists:
                yield dist
        elif subitem.lower().endswith(('.dist-info', '.egg-info')):
            subpath = os.path.join(path_item, subitem)
            submeta = pkg_resources.EggMetadata(zipimport.zipimporter(subpath))
            submeta.egg_info = subpath
            yield pkg_resources.Distribution.from_location(path_item, subitem, submeta)  # noqa: B950
```

Then save the `__boot__.py` file by sudo.

Or you can edit binary of py2app in `venv/lib/python3.11/site-packages/py2app/recipes/setuptools.py` line 21:

```python
if metadata.has_metadata('PKG-INFO'):
    yield Distribution.from_filename(path_item, metadata=metadata)
```

to 

```python
if metadata.has_metadata('PKG-INFO'):
    yield pkg_resources.Distribution.from_filename(path_item, metadata=metadata)
```
