### ISSUE TITLE
Can't run on Windows (Exception from HRESULT: 0x80020101)

### ISSUE THREAD

**Issue by oori** [r0x0r/pywebview-react-boilerplate#7]
Clean git clones.   On windows the `npm run init` runs successfully, but `npm run start` fails: app opens empty, and this exception appears on the console **every second** (_so, probably due to the ticker?_)
```
Traceback (most recent call last):
  File "C:\Users\oori\Downloads\pywebview-react-boilerplate\venv-pywebview\lib\site-packages\webview\platforms\winforms.py", line 267, in evaluate_js
    result = self.web_view.InvokeScript('eval', (script,))
System.AggregateException: One or more errors occurred.
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.InvokeScript(String scriptName, String[] arguments)
[pywebview] Error occurred in script
System.Exception: Exception from HRESULT: 0x80020101
```

Here's a [clue](https://stackoverflow.com/questions/10312088/webview-invokescript-hresult-0x80020101)?
I've tested on macOS and windows10, and this issue only appears on Windows.

**Comment by r0x0r** [comment]
You are trying to run it as admin. Either run it normally or try another
renderer. Search the main repo for this error for more info.
